import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const localesDir = join(__dirname, '..', 'lib', 'i18n', 'locales')

// Complete translations for all 25 non-English languages
// Each language has EVERY key translated professionally

const langs = {
de: {
  common: { home:"Startseite",tours:"Touren",destinations:"Reiseziele",about:"Über uns",contact:"Kontakt",contactUs:"Kontaktieren Sie uns",bookNow:"Jetzt buchen",faq:"FAQ",learnMore:"Mehr erfahren",viewAll:"Alle anzeigen",explore:"Entdecken",submit:"Absenden",sending:"Wird gesendet...",success:"Erfolg!",error:"Fehler",loading:"Lädt...",readMore:"Mehr lesen",viewDetails:"Details anzeigen",back:"Zurück",next:"Weiter",previous:"Vorherige",close:"Schließen",subscribe:"Abonnieren",subscribing:"Wird abonniert...",email:"E-Mail",phone:"Telefon",name:"Name",message:"Nachricht",required:"Erforderlich",optional:"Optional",days:"Tage",nights:"Nächte",perPerson:"pro Person",from:"Ab",included:"Inklusive",notIncluded:"Nicht inklusive",highlights:"Höhepunkte",itinerary:"Reiseplan",pricing:"Preise",tailorTrip:"Reise anpassen",aiTripMaker:"KI-Reiseplaner",partners:"Partner",customize:"Anpassen" },
  header: { jordanTours:"Jordanien Touren",jordanDestinations:"Jordanien Reiseziele" },
  announcement: { freeEsim:"KOSTENLOSE E-SIM mit UNBEGRENZTEN Daten während Ihrer Reise",fullRefund:"Volle Rückerstattung bei Stornierung 30 Tage vor der Reise",emergencyNumber:"24/7 NOTFALLNUMMER für Chat und Anrufe" },
  hero: { badge:"Entdecken Sie antike Wunder",title1:"Reise durch das",title2:"Antike Arabien",subtitle:"Erleben Sie die Magie Jordaniens mit fachmännisch gestalteten Touren, die Geschichte lebendig werden lassen",feature1:"7 UNESCO-Stätten",feature2:"2000+ Jahre Geschichte",feature3:"Erfahrene lokale Reiseführer",exploreTours:"Alle Touren entdecken",planJourney:"Planen Sie Ihre Reise" },
  whyChooseUs: { title:"Warum Jordan Explorer wählen?",subtitle:"Wir sind Ihr All-Inclusive-Tor zum Erleben des Besten von Jordanien.",oneStop:"Alles aus einer Hand",oneStopDesc:"Wir kümmern uns um alles, von Flügen und Hotels bis hin zu Reiseführern und Aktivitäten.",secure:"100% sichere Buchung",secureDesc:"Ihre Zahlungen und persönlichen Daten sind immer geschützt.",guides:"Erfahrene lokale Reiseführer",guidesDesc:"Unsere sachkundigen Reiseführer bieten authentische Einblicke.",customizable:"Anpassbare Pakete",customizableDesc:"Gestalten Sie Ihre Reise mit flexiblen Optionen.",flights:"Flugarrangements",flightsDesc:"Wir kümmern uns um Flugbuchungen und Flughafentransfers.",accommodations:"Premium-Unterkünfte",accommodationsDesc:"Übernachten Sie in sorgfältig ausgewählten Hotels." },
  testimonials: { title:"Was unsere Reisenden sagen",subtitle:"Hören Sie von Reisenden, die die Magie Jordaniens mit uns erlebt haben." },
  featuredDestinations: { title:"Entdecken Sie Jordaniens Schätze",subtitle:"Von antiken Wundern bis zu Naturwundern bietet Jordanien unvergessliche Reiseziele.",viewAll:"Alle Reiseziele anzeigen" },
  newsletter: { title:"Lassen Sie sich für Ihr Jordanien-Abenteuer inspirieren",subtitle:"Abonnieren Sie unseren Newsletter für exklusive Reisetipps und Sonderangebote.",placeholder:"Geben Sie Ihre E-Mail ein",consent:"Mit der Anmeldung stimmen Sie unserer Datenschutzrichtlinie zu.",successMessage:"Sie haben unseren Newsletter abonniert." },
  toursPage: { title:"Unsere Jordanien-Reisepakete",subtitle:"Wählen Sie aus unseren sorgfältig zusammengestellten Reisepaketen.",alert:"Alle Touren können angepasst werden! Wählen Sie Ihre Hotelklasse und klicken Sie auf \"Reise anpassen\".",whyChoose:"Warum unsere Touren wählen?",flexible:"Flexible Anpassung",flexibleDesc:"Jede Tour kann an Ihre Bedürfnisse angepasst werden.",transparent:"Transparente Preise",transparentDesc:"Keine versteckten Gebühren.",expertGuides:"Erfahrene lokale Reiseführer",expertGuidesDesc:"Lizenzierte Reiseführer, die Geschichte lebendig werden lassen.",allInclusive:"All-Inclusive-Pakete",allInclusiveDesc:"Transport, Unterkunft, Mahlzeiten, Eintrittsgebühren inklusive.",needHelp:"Brauchen Sie Hilfe? Unser Team steht Ihnen zur Verfügung." },
  destinationsPage: { title:"Entdecken Sie Jordaniens Schätze",subtitle:"Entdecken Sie die Magie jedes einzigartigen Ortes.",cantDecide:"Können Sie sich nicht entscheiden?",cantDecideDesc:"Unsere Reiseexperten helfen Ihnen bei der Planung.",contactExperts:"Kontaktieren Sie unsere Reiseexperten" },
  destinations: { petra:{name:"Petra",description:"Entdecken Sie die antike Stadt in rosafarbenem Fels"},wadiRum:{name:"Wadi Rum",description:"Erleben Sie außerirdische Wüstenlandschaften"},deadSea:{name:"Totes Meer",description:"Schweben Sie im mineralreichen Wasser"},jerash:{name:"Jerash",description:"Wandeln Sie durch eine der besterhaltenen römischen Städte"},amman:{name:"Amman",description:"Erkunden Sie Jordaniens historische Hauptstadt"},aqaba:{name:"Aqaba",description:"Tauchen Sie in die Gewässer des Roten Meeres"} },
  aboutPage: { badge:"Seit 2015",heroTitle:"Unvergessliche",heroTitle2:"Jordanien-Abenteuer gestalten",heroSubtitle:"Ihr vertrauenswürdiger Partner bei der Erkundung Jordaniens",storyBadge:"Unsere Geschichte",storyTitle:"Aus Leidenschaft für Jordanien geboren",storyP1:"Jordan Explorer wurde 2015 von Reisebegeisterten gegründet, die sich in Jordanien verliebt haben.",storyP2:"Was als kleine Tour-Organisation begann, ist zu einem führenden Reiseunternehmen herangewachsen.",storyP3:"Heute haben wir über 10.000 Reisenden geholfen, Jordanien zu entdecken.",impactTitle:"Unsere Wirkung in Zahlen",impactSubtitle:"Ein Jahrzehnt der Exzellenz",happyTravelers:"Zufriedene Reisende",destinations:"Reiseziele",yearsExperience:"Jahre Erfahrung",averageRating:"Durchschnittliche Bewertung",missionBadge:"Unsere Mission",missionTitle:"Was uns antreibt",missionSubtitle:"Authentische Reiseerlebnisse schaffen, die Menschen mit Jordanien verbinden.",passion:"Leidenschaft für Exzellenz",passionDesc:"Jede Tour wird mit Liebe zum Detail gestaltet.",trust:"Vertrauen & Sicherheit",trustDesc:"Ihre Sicherheit hat oberste Priorität.",cultural:"Kulturelle Authentizität",culturalDesc:"Echte Verbindungen zu lokalen Gemeinschaften.",whyChooseBadge:"Warum uns wählen",whyChooseTitle:"Der Jordan Explorer Unterschied",expertGuides:"Erfahrene lokale Reiseführer",expertGuidesDesc:"Leidenschaftliche Einheimische mit tiefem Wissen.",flexibleItineraries:"Flexible Reisepläne",flexibleItinerariesDesc:"Passen Sie Ihre Tour an Ihre Interessen an.",premiumAccommodations:"Premium-Unterkünfte",premiumAccommodationsDesc:"Sorgfältig ausgewählte 3★, 4★ und 5★ Hotels.",smallGroups:"Kleine Gruppengrößen",smallGroupsDesc:"Persönliche Aufmerksamkeit und bedeutungsvolle Verbindungen.",support247:"24/7 Support",support247Desc:"Unser Team ist jederzeit für Sie da.",bestValue:"Beste Preis-Garantie",bestValueDesc:"Wettbewerbsfähige Preise, kostenlose eSIM und flexible Stornierung.",teamBadge:"Unser Team",teamTitle:"Lernen Sie die Menschen hinter Ihrer Reise kennen",teamSubtitle:"Unser engagiertes Team arbeitet unermüdlich für Ihr Abenteuer.",ctaTitle:"Bereit für Ihr Abenteuer?",ctaSubtitle:"Schließen Sie sich Tausenden zufriedener Reisender an.",exploreTours:"Unsere Touren entdecken" },
  contactPage: { heroTitle:"Kontaktieren Sie uns",heroSubtitle:"Unsere Reiseexperten helfen Ihnen gerne.",formBadge:"Senden Sie uns eine Nachricht",formTitle:"Kontaktieren Sie unser Team",formSubtitle:"Wir melden uns innerhalb von 24 Stunden.",firstName:"Vorname",lastName:"Nachname",emailAddress:"E-Mail-Adresse",phoneNumber:"Telefonnummer (Optional)",subject:"Betreff",subjectPlaceholder:"Touranfrage",messagePlaceholder:"Erzählen Sie uns von Ihren Reiseplänen...",sendMessage:"Nachricht senden",messageSent:"Nachricht gesendet!",thankYou:"Danke! Wir melden uns innerhalb von 24 Stunden.",infoBadge:"Kontaktinformationen",infoTitle:"Erreichen Sie uns direkt",phoneWhatsApp:"Telefon & WhatsApp",phoneDesc:"Jederzeit erreichbar",emergencySupport:"24/7 Notfall-Support",emailTitle:"E-Mail",emailDesc:"Senden Sie uns eine E-Mail",responseTime:"Antwort innerhalb von 24 Stunden",officeTitle:"Bürostandort",officeDesc:"Besuchen Sie uns in Amman",businessHours:"Geschäftszeiten",sundayThursday:"Sonntag - Donnerstag: 9:00 - 18:00 Uhr",friday:"Freitag: Geschlossen",saturday:"Samstag: 10:00 - 16:00 Uhr",whyChooseTitle:"Warum Jordan Explorer wählen?",whyChoose1:"Erfahrene lokale Reiseführer",whyChoose2:"Anpassbare Reisepläne",whyChoose3:"24/7 Support während Ihrer Reise",whyChoose4:"Kostenlose eSIM mit unbegrenzten Daten",faqTitle:"Haben Sie Fragen?",faqSubtitle:"Besuchen Sie unsere FAQ-Seite für Antworten.",viewFaq:"Häufig gestellte Fragen anzeigen" },
  bookNowPage: { badge:"Buchen Sie Ihre Traumreise",heroTitle:"Buchung abschließen",heroSubtitle:"Wir melden uns innerhalb von 24 Stunden",tourSelection:"Tourauswahl",tourSelectionDesc:"Wählen Sie Ihr Reisepaket",selectTour:"Tour auswählen",chooseTour:"Tour wählen...",travelDetails:"Reisedetails",travelDetailsDesc:"Wann möchten Sie reisen?",departureDate:"Abreisedatum",pickDate:"Datum wählen",groupSize:"Gruppengröße",people:"Personen",hotelClass:"Hotelklasse",comfortable:"Komfortabel",superior:"Superior",luxury:"Luxus",yourInfo:"Ihre Informationen",yourInfoDesc:"Zur Bestätigung Ihrer Buchung",countryResidence:"Wohnsitzland",specialRequests:"Besondere Wünsche (Optional)",specialRequestsPlaceholder:"Diät, Barrierefreiheit, besondere Anlässe...",submitBooking:"Buchungsanfrage absenden",bookingConfirmed:"Buchungsanfrage gesendet!",thankYouBooking:"Danke! Wir kontaktieren Sie innerhalb von 24 Stunden.",summaryTitle:"Buchungsübersicht",selectTourSummary:"Tour auswählen für Preisdetails",departure:"Abreise:",season:"Saison:",highSeason:"Hochsaison",lowSeason:"Nebensaison",pricePerPerson:"Preis pro Person:",totalEstimate:"Geschätzte Gesamtsumme:",basedOn:"*Basierend auf {count} Reisenden.",whatsIncluded:"Inklusive",freeEsim:"Kostenlose eSIM mit unbegrenzten Daten",expertGuides:"Erfahrene Reiseführer",entranceFees:"Alle Eintrittsgebühren",hotelAccommodations:"Hotelunterkünfte",dailyBreakfast:"Tägliches Frühstück",cancellationTitle:"Stornierungsbedingungen",cancellationDesc:"Volle Rückerstattung bei Stornierung 30 Tage vorher" },
  faqPage: { heroTitle:"Häufig gestellte Fragen",heroSubtitle:"Alles über das Reisen mit Jordan Explorer.",generalQuestions:"Allgemeine Fragen",generalBadge:"Allgemeine Informationen",generalSubtitle:"Häufige Fragen zum Buchen und Reisen",jordanFaqs:"Jordanien Reise-FAQs",jordanBadge:"Jordanien",jordanSubtitle:"Wichtige Informationen für Jordanien",stillHaveQuestions:"Noch Fragen?",stillHaveQuestionsDesc:"Kontaktieren Sie uns per WhatsApp, E-Mail oder Telefon.",browseTours:"Touren durchsuchen",q1:"Wie buche ich eine Tour?",a1:"Durchsuchen Sie unsere Touren, wählen Sie Ihr Paket und klicken Sie auf \"Jetzt buchen\". 30% Anzahlung erforderlich.",q2:"Wie ist Ihre Stornierungsrichtlinie?",a2:"Volle Rückerstattung bei 30+ Tagen. 50% bei 15-29 Tagen. Nicht erstattbar innerhalb von 14 Tagen.",q3:"Welche Gruppengrößen?",a3:"Alle Größen! Preise für 2-15+ Personen. Sonderpreise für Gruppen über 15.",q4:"Beste Reisezeit?",a4:"Frühling (März-Mai) und Herbst (September-November) sind ideal.",q5:"Kostenlose eSIM?",a5:"Ja! Alle Kunden erhalten eine kostenlose eSIM mit unbegrenzten Daten.",q6:"Was ist im Preis enthalten?",a6:"Unterkunft, Transport, Reiseführer, Eintrittsgebühren, Mahlzeiten, Transfers und eSIM.",q7:"Kann ich die Route anpassen?",a7:"Ja! Klicken Sie auf \"Reise anpassen\" für individuelle Änderungen.",jq1:"Brauche ich ein Visum?",ja1:"Visum bei Ankunft möglich. 40 JOD. Mit Jordan Pass entfällt die Gebühr bei 3+ Nächten.",jq2:"Was einpacken?",ja2:"Bequeme Schuhe, bescheidene Kleidung, Sonnenschutz, Schichten, Kamera.",jq3:"Ist Jordanien sicher?",ja3:"Ja! Eines der sichersten Länder im Nahen Osten.",jq4:"Welche Währung?",ja4:"Jordanischer Dinar (JOD). 1 JOD ≈ 1,41 USD. Geldautomaten verfügbar.",jq5:"Wie viel Zeit für Petra?",ja5:"Mindestens ein voller Tag. 6-8 Stunden für die Highlights." },
  footer: { description:"Ihre Lösung für unvergessliche Jordanien-Abenteuer.",quickLinks:"Schnelllinks",toursPackages:"Touren & Pakete",travelBlog:"Reiseblog",faqs:"FAQs",contactUs:"Kontakt",newsletterTitle:"Newsletter",newsletterDesc:"Sonderangebote und Reiseinspiration.",emailPlaceholder:"Ihre E-Mail-Adresse",copyright:"Jordan Explorer. Alle Rechte vorbehalten.",terms:"AGB",privacy:"Datenschutz",cookies:"Cookie-Richtlinie" },
  homePage: { jordanToursBadge:"Jordanien entdecken",jordanToursTitle:"Unsere Jordanien-Reisepakete",jordanToursDesc:"Von Petra über Wadi Rum bis zum Toten Meer.",viewAllJordan:"Alle Jordanien-Touren",historyBadge:"Jordanien erkunden",historyTitle:"Jordaniens reiche Geschichte",historyDesc:"Bemerkenswerte historische Stätten und biblische Sehenswürdigkeiten.",journeyTime:"Eine Reise durch die Zeit",journeyTimeDesc:"Tausende Jahre Geschichte mit Nabatäern, Römern, Byzantinern.",petraTitle:"Petra",petraDesc:"Antike Stadt in rosafarbenem Fels",jerashTitle:"Jerash",jerashDesc:"Gut erhaltene römische Stadt",mountNeboTitle:"Berg Nebo",mountNeboDesc:"Wo Moses das Gelobte Land sah",desertCastlesTitle:"Wüstenschlösser",desertCastlesDesc:"Frühislamische Kunst und Architektur",exploreHistorical:"Historische Stätten erkunden",tourOptionsBadge:"Touroptionen",tourOptionsTitle:"Wählen Sie Ihre perfekte Reise",tourOptionsDesc:"Mehrere Tourdauern, anpassbar nach Ihren Wünschen.",travelTipsBadge:"Reisetipps",travelTipsTitle:"Vorbereitung auf Ihr Abenteuer",travelTipsDesc:"Hilfreiche Tipps zum Reisen in Jordanien.",culturalEtiquette:"Kulturelle Etikette",culturalEtiquetteDesc:"Lokale Bräuche und Traditionen kennenlernen.",weatherPacking:"Wetter & Packen",weatherPackingDesc:"Was einpacken und wann reisen.",cuisineDining:"Küche & Essen",cuisineDiningDesc:"Köstliche jordanische Küche entdecken." },
  partnersPage: { badge:"B2B-Partnerprogramm",heroTitle:"Ihr Bodenpartner in Jordanien",heroSubtitle:"Wir kümmern uns um alles vor Ort. Sie verkaufen und bestimmen Ihre Margen.",becomePartner:"Partner werden",requestRateSheet:"Preisliste anfordern",whyPartnerTitle:"Warum mit uns zusammenarbeiten?",whyPartnerSubtitle:"Lizenziertes DMC in Jordanien für europäische Reisebüros.",localExpertise:"Lokale Expertise",localExpertiseDesc:"Tiefes lokales Wissen über Hotels, Routen und Geheimtipps.",b2bNetRates:"B2B-Nettopreise",b2bNetRatesDesc:"Wettbewerbsfähige Nettopreise ohne versteckte Gebühren.",whiteLabelService:"White-Label-Service",whiteLabelServiceDesc:"Wir arbeiten unter Ihrer Marke.",multiLanguageGuides:"Mehrsprachige Reiseführer",multiLanguageGuidesDesc:"Lizenzierte Guides in vielen Sprachen.",allHotelClasses:"Alle Hotelklassen",allHotelClassesDesc:"Von 3★ bis 5★ Luxus.",support247:"24/7 Support",support247Desc:"Notfall-Support rund um die Uhr.",servicesTitle:"Unsere Dienstleistungen",service1:"Private Flughafentransfers",service2:"Hotelbuchungen (3★ bis 5★)",service3:"Professionelle Reiseführer",service4:"4x4 Wüsten-Jeep-Touren",service5:"Beduinen-Camping & Glamping",service6:"Totes-Meer-Resort",service7:"Petra bei Tag & Nacht",service8:"Kochkurse & Kultur",service9:"Dana Naturreservat Trekking",service10:"Aqaba Tauchen & Schnorcheln",service11:"Jordan-Pass",service12:"Individuelle Reiseplanung",popularPrograms:"Beliebteste Programme",mostRequested:"Am meisten nachgefragt",requestNetRates:"Nettopreise anfordern",program1Days:"3 Tage",program1Title:"Petra & Wadi Rum Express",program2Days:"5 Tage",program2Title:"Klassisches Jordanien",program3Days:"8 Tage",program3Title:"Volle Entdeckung",formTitle:"Partner werden",formSubtitle:"B2B-Preisliste innerhalb von 24 Stunden.",companyName:"Firmenname",contactPerson:"Ansprechpartner",businessEmail:"Geschäfts-E-Mail",phoneWhatsApp:"Telefon / WhatsApp",website:"Website",country:"Land",selectCountry:"Land auswählen",annualClients:"Jährliche Kunden",approximateVolume:"Ungefähres Volumen",additionalInfo:"Zusätzliche Informationen",additionalInfoPlaceholder:"Ihre Bedürfnisse...",submitInquiry:"Anfrage senden",thankYou:"Vielen Dank!",thankYouDesc:"Preisliste innerhalb von 24 Stunden.",backToHome:"Zur Startseite",inquirySent:"Anfrage gesendet!",inquirySentDesc:"Wir melden uns innerhalb von 24 Stunden.",errorTitle:"Fehler aufgetreten",errorDesc:"Bitte direkt per E-Mail kontaktieren." },
  thankYouPage: { title:"Vielen Dank!",subtitle:"Ihre Anfrage wurde empfangen.",whatHappensNext:"Was passiert als Nächstes?",whatHappensNextDesc:"Das erwartet Sie",within24Hours:"Innerhalb von 24 Stunden",within24HoursDesc:"Detailliertes Angebot mit Preisen und Verfügbarkeit.",checkEmail:"E-Mail prüfen",checkEmailDesc:"Bestätigungs-E-Mail kommt in Kürze.",finalizeTrip:"Reise finalisieren",finalizeTripDesc:"Letzte Anpassungen und Buchung bestätigen.",needHelp:"Sofortige Hilfe?",callAnytime:"Jederzeit anrufen",available247:"24/7 erreichbar",emailUs:"E-Mail senden",detailedInquiries:"Für detaillierte Anfragen",respondTime:"Antwort innerhalb von 2 Stunden",whileYouWait:"Während Sie warten...",whileYouWaitDesc:"Mehr über Jordanien erfahren!",travelGuide:"Reiseführer",travelGuideDesc:"Kultur und Sehenswürdigkeiten",readGuide:"Leitfaden lesen →",destinationsTitle:"Reiseziele",destinationsDesc:"Entdecken Sie die Orte Ihrer Tour",exploreLink:"Entdecken →",otherTours:"Andere Touren",otherToursDesc:"Weitere Tourpakete durchsuchen",viewToursLink:"Touren ansehen →",returnHome:"Zur Startseite",requestConfirmed:"Anfrage bestätigt" },
  customizePage: { title:"Jordanien-Erlebnis anpassen",subtitle:"Ihre perfekte Reise gestalten.",step1:"Tour & Daten",step2:"Hotels & Extras",step3:"Kontaktdaten",selectTourDates:"Tour & Daten auswählen",chooseYourTour:"Tour wählen",startDate:"Startdatum",numberOfTravelers:"Reisende",adults:"Erwachsene (18+)",children:"Kinder (0-17)",totalTravelers:"Gesamt:",arrivalFlight:"Ankunftsflug (optional)",arrivalTime:"Ankunftszeit (optional)",pickupLocation:"Abholort",nextHotels:"Weiter: Hotels & Extras",chooseHotelsAddons:"Hotels & Extras wählen",hotelClass:"Hotelklasse",sampleHotels:"Beispielhotels:",dietaryRequirements:"Ernährung (optional)",dietaryPlaceholder:"z.B. Vegetarisch, Vegan",roomingPreferences:"Zimmerpräferenzen (optional)",roomingPlaceholder:"z.B. Einzelbetten",optionalAddons:"Optionale Extras",nextContact:"Weiter: Kontaktdaten",yourContactInfo:"Kontaktinformationen",fullName:"Vollständiger Name",emailAddress:"E-Mail-Adresse",phoneNumber:"Telefonnummer",whatsappNumber:"WhatsApp (optional)",whatsappDesc:"Für schnelle Kommunikation",additionalNotes:"Anmerkungen (optional)",additionalNotesPlaceholder:"Besondere Wünsche...",consentText:"Ich stimme der Kontaktaufnahme zu.",submitRequest:"Anfrage absenden",priceEstimate:"Preisschätzung",selectedTour:"Ausgewählte Tour",travelers:"Reisende:",season:"Saison:",basePrice:"Grundpreis:",addons:"Extras:",singleSupplement:"Einzelzimmerzuschlag:",totalEstimate:"Gesamtschätzung:",perPerson:"pro Person",estimateNote:"Geschätzter Preis. Endpreis wird bestätigt.",selectTourToSee:"Tour auswählen für Preise",whatHappensNext:"Was passiert als Nächstes?",review24h:"Prüfung innerhalb von 24 Stunden",detailedQuote:"Detailliertes Angebot",finalAdjustments:"Letzte Anpassungen",confirmBooking:"Buchung bestätigen" },
  aiTripMaker: { badge:"Intelligenter Reiseplaner",heroTitle:"Gestalten Sie Ihre perfekte Reise",heroSubtitle:"Beantworten Sie einige Fragen für Ihre personalisierte Reiseroute",step:"Schritt",of:"von",complete:"Abgeschlossen",whereToGo:"Wohin möchten Sie?",selectCountries:"Bis zu 3 Länder wählen",citiesAvailable:"Städte verfügbar",whichCities:"Welche Städte interessieren Sie?",selectCities:"Städte zum Erkunden wählen",whatExperiences:"Welche Erlebnisse begeistern Sie?",chooseActivities:"Aktivitäten auswählen",whenTraveling:"Wann reisen Sie?",tellTimeline:"Reisezeitraum",tripDuration:"Reisedauer",selectDuration:"Dauer wählen",preferredDates:"Bevorzugte Daten",whatsYourBudget:"Ihr Budget?",tailorExperience:"Das perfekte Erlebnis gestalten",budgetPerPerson:"Budget pro Person (USD)",selectBudget:"Budgetbereich wählen",accommodationPref:"Unterkunftspräferenz",comfortable:"Komfortabel",superiorComfort:"Gehobener Komfort",luxuryExperience:"Luxuserlebnis",tellAboutGroup:"Ihre Gruppe",specialRequirements:"Besondere Anforderungen?",numberOfTravelers:"Anzahl Reisende",selectGroupSize:"Gruppengröße wählen",soloTraveler:"Alleinreisender",people2:"2 Personen",people35:"3-5 Personen",people67:"6-7 Personen",people8plus:"8+ Personen",specialRequestsLabel:"Besondere Wünsche (Optional)",specialRequestsPlaceholder:"Ernährung, Barrierefreiheit, besondere Anlässe...",almostThere:"Fast geschafft!",sendItinerary:"Wohin senden?",fullName:"Vollständiger Name",emailAddress:"E-Mail-Adresse",phoneOptional:"Telefon (Optional)",tripSummary:"Reisezusammenfassung",countriesLabel:"Länder:",citiesLabel:"Städte:",activitiesLabel:"Aktivitäten:",durationLabel:"Dauer:",budgetLabel:"Budget:",accommodationLabel:"Unterkunft:",groupSizeLabel:"Gruppengröße:",selected:"ausgewählt",daysLabel:"Tage",travelers:"Reisende",continueBtn:"Weiter",sendItineraryBtn:"Reiseroute senden",jeepTours:"Jeep-Touren",jeepToursDesc:"Offroad-Wüstenabenteuer",divingSnorkeling:"Tauchen & Schnorcheln",divingSnorkelingDesc:"Unterwasserwelten",hotAirBalloon:"Heißluftballon",hotAirBalloonDesc:"Landschaften von oben",sandboarding:"Sandboarding",sandboardingDesc:"Dünen surfen",historicalSites:"Historische Stätten",historicalSitesDesc:"Antike Ruinen",photographyTours:"Fototouren",photographyToursDesc:"Momente einfangen",culinaryExperiences:"Kulinarische Erlebnisse",culinaryExperiencesDesc:"Lokale Küche",shoppingSouks:"Shopping & Souks",shoppingSouksDesc:"Traditionelle Märkte",desertCamping:"Wüstencamping",desertCampingDesc:"Unter Sternen schlafen",jordan:"Jordanien",egypt:"Ägypten",saudiArabia:"Saudi-Arabien",countrySelected:"Land ausgewählt",countriesSelected:"Länder ausgewählt" },
},
fr: {
  common: { home:"Accueil",tours:"Circuits",destinations:"Destinations",about:"À propos",contact:"Contact",contactUs:"Contactez-nous",bookNow:"Réserver",faq:"FAQ",learnMore:"En savoir plus",viewAll:"Tout voir",explore:"Explorer",submit:"Envoyer",sending:"Envoi...",success:"Succès !",error:"Erreur",loading:"Chargement...",readMore:"Lire la suite",viewDetails:"Voir les détails",back:"Retour",next:"Suivant",previous:"Précédent",close:"Fermer",subscribe:"S'abonner",subscribing:"Abonnement...",email:"E-mail",phone:"Téléphone",name:"Nom",message:"Message",required:"Obligatoire",optional:"Facultatif",days:"Jours",nights:"Nuits",perPerson:"par personne",from:"À partir de",included:"Inclus",notIncluded:"Non inclus",highlights:"Points forts",itinerary:"Itinéraire",pricing:"Tarifs",tailorTrip:"Personnaliser ce voyage",aiTripMaker:"Créateur de voyage IA",partners:"Partenaires",customize:"Personnaliser" },
  header: { jordanTours:"Circuits en Jordanie",jordanDestinations:"Destinations en Jordanie" },
  announcement: { freeEsim:"E-SIM GRATUITE avec données ILLIMITÉES pendant votre voyage",fullRefund:"Remboursement intégral si annulation 30 jours avant",emergencyNumber:"NUMÉRO D'URGENCE 24h/24 7j/7" },
  hero: { badge:"Découvrez les merveilles antiques",title1:"Voyage à travers",title2:"l'Arabie antique",subtitle:"Vivez la magie de la Jordanie avec des circuits qui donnent vie à l'histoire",feature1:"7 sites UNESCO",feature2:"2000+ ans d'histoire",feature3:"Guides locaux experts",exploreTours:"Explorer tous les circuits",planJourney:"Planifiez votre voyage" },
  whyChooseUs: { title:"Pourquoi choisir Jordan Explorer ?",subtitle:"Votre solution tout-en-un pour découvrir le meilleur de la Jordanie.",oneStop:"Solution tout-en-un",oneStopDesc:"Nous gérons tout pour une expérience fluide.",secure:"Réservation 100% sécurisée",secureDesc:"Vos paiements sont toujours protégés.",guides:"Guides locaux experts",guidesDesc:"Des perspectives authentiques et une expérience inoubliable.",customizable:"Forfaits personnalisables",customizableDesc:"Options flexibles pour votre aventure parfaite.",flights:"Organisation des vols",flightsDesc:"Vols et transferts aéroport sans stress.",accommodations:"Hébergements premium",accommodationsDesc:"Hôtels soigneusement sélectionnés." },
  testimonials: { title:"Ce que disent nos voyageurs",subtitle:"Écoutez ceux qui ont vécu la magie de la Jordanie avec nous." },
  featuredDestinations: { title:"Explorez les trésors de la Jordanie",subtitle:"Des merveilles antiques aux merveilles naturelles.",viewAll:"Voir toutes les destinations" },
  newsletter: { title:"Inspirez-vous pour votre aventure jordanienne",subtitle:"Conseils exclusifs, offres spéciales et histoires inspirantes.",placeholder:"Votre e-mail",consent:"Vous acceptez notre politique de confidentialité.",successMessage:"Vous êtes inscrit à notre newsletter." },
  toursPage: { title:"Nos forfaits circuits en Jordanie",subtitle:"Choisissez parmi nos forfaits soigneusement conçus.",alert:"Tous les circuits sont personnalisables !",whyChoose:"Pourquoi nos circuits ?",flexible:"Personnalisation flexible",flexibleDesc:"Chaque circuit adapté à vos besoins.",transparent:"Tarification transparente",transparentDesc:"Pas de frais cachés.",expertGuides:"Guides locaux experts",expertGuidesDesc:"Guides agréés qui donnent vie à l'histoire.",allInclusive:"Forfaits tout compris",allInclusiveDesc:"Transport, hébergement, repas, droits d'entrée inclus.",needHelp:"Besoin d'aide ? Notre équipe est là." },
  destinationsPage: { title:"Explorez les trésors de la Jordanie",subtitle:"Découvrez la magie de chaque lieu unique.",cantDecide:"Vous n'arrivez pas à décider ?",cantDecideDesc:"Nos experts planifient l'itinéraire parfait pour vous.",contactExperts:"Contactez nos experts voyage" },
  destinations: { petra:{name:"Pétra",description:"Cité antique sculptée dans la roche rose"},wadiRum:{name:"Wadi Rum",description:"Paysages désertiques d'un autre monde"},deadSea:{name:"Mer Morte",description:"Flottez dans les eaux riches en minéraux"},jerash:{name:"Jérash",description:"Ville romaine remarquablement préservée"},amman:{name:"Amman",description:"Capitale vibrante et historique"},aqaba:{name:"Aqaba",description:"Eaux cristallines de la mer Rouge"} },
  aboutPage: { badge:"Depuis 2015",heroTitle:"Créer des aventures",heroTitle2:"inoubliables en Jordanie",heroSubtitle:"Votre partenaire de confiance pour explorer la Jordanie",storyBadge:"Notre histoire",storyTitle:"Né d'une passion pour la Jordanie",storyP1:"Fondé en 2015 par des passionnés de voyage amoureux de la Jordanie.",storyP2:"D'une petite opération à une entreprise de voyage de premier plan.",storyP3:"Plus de 10 000 voyageurs ont découvert la magie de la Jordanie.",impactTitle:"Notre impact en chiffres",impactSubtitle:"Une décennie d'excellence",happyTravelers:"Voyageurs satisfaits",destinations:"Destinations",yearsExperience:"Années d'expérience",averageRating:"Note moyenne",missionBadge:"Notre mission",missionTitle:"Ce qui nous motive",missionSubtitle:"Créer des expériences authentiques connectant les gens à la Jordanie.",passion:"Passion pour l'excellence",passionDesc:"Attention méticuleuse aux détails.",trust:"Confiance et sécurité",trustDesc:"Votre sécurité est notre priorité.",cultural:"Authenticité culturelle",culturalDesc:"Connexions authentiques avec les communautés locales.",whyChooseBadge:"Pourquoi nous choisir",whyChooseTitle:"La différence Jordan Explorer",expertGuides:"Guides locaux experts",expertGuidesDesc:"Locaux passionnés avec une connaissance approfondie.",flexibleItineraries:"Itinéraires flexibles",flexibleItinerariesDesc:"Personnalisez selon vos intérêts.",premiumAccommodations:"Hébergements premium",premiumAccommodationsDesc:"Hôtels 3★, 4★ et 5★ sélectionnés.",smallGroups:"Petits groupes",smallGroupsDesc:"Attention personnalisée et connexions significatives.",support247:"Support 24h/24",support247Desc:"Toujours disponible pour vous aider.",bestValue:"Meilleur rapport qualité-prix",bestValueDesc:"Prix compétitifs, eSIM gratuite, annulation flexible.",teamBadge:"Notre équipe",teamTitle:"Les personnes derrière votre voyage",teamSubtitle:"Une équipe dédiée pour une aventure extraordinaire.",ctaTitle:"Prêt pour l'aventure ?",ctaSubtitle:"Rejoignez des milliers de voyageurs satisfaits.",exploreTours:"Explorer nos circuits" },
  contactPage: { heroTitle:"Contactez-nous",heroSubtitle:"Nos experts sont là pour vous aider.",formBadge:"Envoyez-nous un message",formTitle:"Contactez notre équipe",formSubtitle:"Réponse dans les 24 heures.",firstName:"Prénom",lastName:"Nom",emailAddress:"Adresse e-mail",phoneNumber:"Téléphone (Facultatif)",subject:"Sujet",subjectPlaceholder:"Demande de circuit",messagePlaceholder:"Vos projets de voyage...",sendMessage:"Envoyer",messageSent:"Message envoyé !",thankYou:"Merci ! Réponse sous 24 heures.",infoBadge:"Coordonnées",infoTitle:"Contactez-nous directement",phoneWhatsApp:"Téléphone & WhatsApp",phoneDesc:"Disponible à tout moment",emergencySupport:"Support d'urgence 24h/24",emailTitle:"E-mail",emailDesc:"Envoyez-nous un e-mail",responseTime:"Réponse sous 24 heures",officeTitle:"Bureau",officeDesc:"Visitez-nous à Amman",businessHours:"Heures d'ouverture",sundayThursday:"Dimanche - Jeudi : 9h - 18h",friday:"Vendredi : Fermé",saturday:"Samedi : 10h - 16h",whyChooseTitle:"Pourquoi Jordan Explorer ?",whyChoose1:"Guides locaux experts",whyChoose2:"Itinéraires personnalisables",whyChoose3:"Support 24h/24",whyChoose4:"eSIM gratuite avec données illimitées",faqTitle:"Des questions ?",faqSubtitle:"Consultez notre FAQ.",viewFaq:"Voir les questions fréquentes" },
  bookNowPage: { badge:"Réservez votre voyage de rêve",heroTitle:"Finalisez votre réservation",heroSubtitle:"Réponse dans les 24 heures",tourSelection:"Sélection du circuit",tourSelectionDesc:"Choisissez votre forfait",selectTour:"Sélectionner",chooseTour:"Choisir un circuit...",travelDetails:"Détails du voyage",travelDetailsDesc:"Quand souhaitez-vous voyager ?",departureDate:"Date de départ",pickDate:"Choisir une date",groupSize:"Taille du groupe",people:"Personnes",hotelClass:"Classe d'hôtel",comfortable:"Confortable",superior:"Supérieur",luxury:"Luxe",yourInfo:"Vos informations",yourInfoDesc:"Pour confirmer votre réservation",countryResidence:"Pays de résidence",specialRequests:"Demandes spéciales (Facultatif)",specialRequestsPlaceholder:"Régime, accessibilité, occasions...",submitBooking:"Soumettre la réservation",bookingConfirmed:"Demande envoyée !",thankYouBooking:"Merci ! Confirmation sous 24 heures.",summaryTitle:"Résumé",selectTourSummary:"Sélectionnez un circuit pour les tarifs",departure:"Départ :",season:"Saison :",highSeason:"Haute saison",lowSeason:"Basse saison",pricePerPerson:"Prix par personne :",totalEstimate:"Estimation totale :",basedOn:"*Basé sur {count} voyageurs.",whatsIncluded:"Inclus",freeEsim:"eSIM gratuite illimitée",expertGuides:"Guides experts",entranceFees:"Droits d'entrée",hotelAccommodations:"Hébergement",dailyBreakfast:"Petit-déjeuner quotidien",cancellationTitle:"Politique d'annulation",cancellationDesc:"Remboursement intégral si annulation 30 jours avant" },
  faqPage: { heroTitle:"Questions fréquentes",heroSubtitle:"Tout sur les voyages avec Jordan Explorer.",generalQuestions:"Questions générales",generalBadge:"Informations générales",generalSubtitle:"Questions courantes",jordanFaqs:"FAQ Jordanie",jordanBadge:"Jordanie",jordanSubtitle:"Informations essentielles",stillHaveQuestions:"Encore des questions ?",stillHaveQuestionsDesc:"Contactez-nous via WhatsApp, e-mail ou téléphone.",browseTours:"Parcourir les circuits",q1:"Comment réserver ?",a1:"Parcourez nos circuits, choisissez et cliquez sur \"Réserver\". Acompte de 30% requis.",q2:"Politique d'annulation ?",a2:"Remboursement intégral à 30+ jours. 50% à 15-29 jours. Non remboursable sous 14 jours.",q3:"Tailles de groupe ?",a3:"Toutes tailles ! Tarifs pour 2-15+ personnes.",q4:"Meilleure période ?",a4:"Printemps (mars-mai) et automne (septembre-novembre).",q5:"eSIM gratuite ?",a5:"Oui ! eSIM GRATUITE avec données ILLIMITÉES.",q6:"Qu'est-ce qui est inclus ?",a6:"Hébergement, transport, guides, entrées, repas, transferts et eSIM.",q7:"Personnalisation possible ?",a7:"Oui ! Cliquez sur \"Personnaliser ce voyage\".",jq1:"Visa nécessaire ?",ja1:"Visa à l'arrivée pour la plupart. 40 JOD. Gratuit avec Jordan Pass (3+ nuits).",jq2:"Quoi emporter ?",ja2:"Chaussures confortables, vêtements modestes, protection solaire, couches.",jq3:"Sécurité ?",ja3:"Oui ! L'un des pays les plus sûrs du Moyen-Orient.",jq4:"Quelle monnaie ?",ja4:"Dinar jordanien (JOD). 1 JOD ≈ 1,41 USD.",jq5:"Temps pour Pétra ?",ja5:"Au moins une journée complète. 6-8 heures pour les highlights." },
  footer: { description:"Votre solution pour des aventures inoubliables en Jordanie.",quickLinks:"Liens rapides",toursPackages:"Circuits & Forfaits",travelBlog:"Blog voyage",faqs:"FAQ",contactUs:"Contact",newsletterTitle:"Newsletter",newsletterDesc:"Offres spéciales et inspiration.",emailPlaceholder:"Votre e-mail",copyright:"Jordan Explorer. Tous droits réservés.",terms:"Conditions générales",privacy:"Confidentialité",cookies:"Cookies" },
  homePage: { jordanToursBadge:"Découvrir la Jordanie",jordanToursTitle:"Nos forfaits circuits",jordanToursDesc:"De Pétra au Wadi Rum et à la mer Morte.",viewAllJordan:"Voir tous les circuits",historyBadge:"Explorer la Jordanie",historyTitle:"L'histoire riche de la Jordanie",historyDesc:"Sites historiques remarquables et sites bibliques.",journeyTime:"Un voyage dans le temps",journeyTimeDesc:"Des milliers d'années d'histoire et de civilisations.",petraTitle:"Pétra",petraDesc:"Cité antique dans la roche rose",jerashTitle:"Jérash",jerashDesc:"Ville romaine bien préservée",mountNeboTitle:"Mont Nébo",mountNeboDesc:"Où Moïse vit la Terre Promise",desertCastlesTitle:"Châteaux du désert",desertCastlesDesc:"Art islamique primitif",exploreHistorical:"Explorer les sites historiques",tourOptionsBadge:"Options de circuits",tourOptionsTitle:"Choisissez votre voyage",tourOptionsDesc:"Plusieurs durées, personnalisables selon vos souhaits.",travelTipsBadge:"Conseils voyage",travelTipsTitle:"Préparez votre aventure",travelTipsDesc:"Conseils utiles pour la Jordanie.",culturalEtiquette:"Étiquette culturelle",culturalEtiquetteDesc:"Coutumes et traditions locales.",weatherPacking:"Météo et bagages",weatherPackingDesc:"Quoi emporter et quand visiter.",cuisineDining:"Cuisine et gastronomie",cuisineDiningDesc:"Saveurs et plats uniques de Jordanie." },
  partnersPage: { badge:"Programme B2B",heroTitle:"Votre partenaire terrain en Jordanie",heroSubtitle:"Nous gérons tout sur place. Vous vendez et fixez vos marges.",becomePartner:"Devenir partenaire",requestRateSheet:"Demander les tarifs",whyPartnerTitle:"Pourquoi s'associer avec nous ?",whyPartnerSubtitle:"DMC agréé au service des agences européennes.",localExpertise:"Expertise locale",localExpertiseDesc:"Connaissance approfondie du terrain.",b2bNetRates:"Tarifs nets B2B",b2bNetRatesDesc:"Tarifs compétitifs, pricing transparent.",whiteLabelService:"Marque blanche",whiteLabelServiceDesc:"Nous opérons sous votre marque.",multiLanguageGuides:"Guides multilingues",multiLanguageGuidesDesc:"Guides en plusieurs langues.",allHotelClasses:"Toutes classes d'hôtels",allHotelClassesDesc:"De 3★ à 5★ luxe.",support247:"Support 24h/24",support247Desc:"Support d'urgence permanent.",servicesTitle:"Nos services",service1:"Transferts privés aéroport",service2:"Réservations hôtels (3★ à 5★)",service3:"Guides professionnels",service4:"Jeep 4x4 Wadi Rum",service5:"Camping & glamping bédouin",service6:"Resort mer Morte",service7:"Pétra jour & nuit",service8:"Cours de cuisine",service9:"Trekking Dana",service10:"Plongée Aqaba",service11:"Jordan Pass",service12:"Itinéraires sur mesure",popularPrograms:"Programmes populaires",mostRequested:"Le plus demandé",requestNetRates:"Demander les tarifs nets",program1Days:"3 Jours",program1Title:"Pétra & Wadi Rum Express",program2Days:"5 Jours",program2Title:"Jordanie classique",program3Days:"8 Jours",program3Title:"Découverte complète",formTitle:"Devenir partenaire",formSubtitle:"Grille tarifaire sous 24 heures.",companyName:"Nom de l'entreprise",contactPerson:"Contact",businessEmail:"E-mail pro",phoneWhatsApp:"Téléphone / WhatsApp",website:"Site web",country:"Pays",selectCountry:"Sélectionner",annualClients:"Clients annuels",approximateVolume:"Volume approximatif",additionalInfo:"Informations supplémentaires",additionalInfoPlaceholder:"Vos besoins...",submitInquiry:"Soumettre",thankYou:"Merci !",thankYouDesc:"Grille tarifaire sous 24 heures.",backToHome:"Retour à l'accueil",inquirySent:"Demande envoyée !",inquirySentDesc:"Réponse sous 24 heures.",errorTitle:"Erreur",errorDesc:"Contactez info@exploringjordan.com" },
  thankYouPage: { title:"Merci !",subtitle:"Votre demande a été reçue.",whatHappensNext:"Et maintenant ?",whatHappensNextDesc:"Ce qui vous attend",within24Hours:"Sous 24 heures",within24HoursDesc:"Devis détaillé avec prix et disponibilité.",checkEmail:"Vérifiez votre e-mail",checkEmailDesc:"E-mail de confirmation envoyé.",finalizeTrip:"Finalisez votre voyage",finalizeTripDesc:"Derniers ajustements et confirmation.",needHelp:"Aide immédiate ?",callAnytime:"Appelez-nous",available247:"Disponible 24h/24",emailUs:"Envoyez un e-mail",detailedInquiries:"Demandes détaillées",respondTime:"Réponse sous 2 heures",whileYouWait:"En attendant...",whileYouWaitDesc:"Explorez la Jordanie !",travelGuide:"Guide de voyage",travelGuideDesc:"Culture et attractions",readGuide:"Lire →",destinationsTitle:"Destinations",destinationsDesc:"Lieux de votre circuit",exploreLink:"Explorer →",otherTours:"Autres circuits",otherToursDesc:"Nos autres forfaits",viewToursLink:"Voir les circuits →",returnHome:"Retour à l'accueil",requestConfirmed:"Demande confirmée" },
  customizePage: { title:"Personnalisez votre voyage",subtitle:"Créez votre aventure jordanienne parfaite.",step1:"Circuit & Dates",step2:"Hôtels & Options",step3:"Coordonnées",selectTourDates:"Sélection circuit & dates",chooseYourTour:"Choisir un circuit",startDate:"Date de début",numberOfTravelers:"Nombre de voyageurs",adults:"Adultes (18+)",children:"Enfants (0-17)",totalTravelers:"Total :",arrivalFlight:"Vol d'arrivée (facultatif)",arrivalTime:"Heure d'arrivée (facultatif)",pickupLocation:"Lieu de prise en charge",nextHotels:"Suivant : Hôtels",chooseHotelsAddons:"Hôtels & Options",hotelClass:"Classe d'hôtel",sampleHotels:"Exemples :",dietaryRequirements:"Régime alimentaire (facultatif)",dietaryPlaceholder:"ex. Végétarien, Végan",roomingPreferences:"Préférences chambre (facultatif)",roomingPlaceholder:"ex. Lits jumeaux",optionalAddons:"Options supplémentaires",nextContact:"Suivant : Coordonnées",yourContactInfo:"Vos coordonnées",fullName:"Nom complet",emailAddress:"E-mail",phoneNumber:"Téléphone",whatsappNumber:"WhatsApp (facultatif)",whatsappDesc:"Pour communication rapide",additionalNotes:"Notes (facultatif)",additionalNotesPlaceholder:"Demandes spéciales...",consentText:"J'accepte d'être contacté.",submitRequest:"Soumettre",priceEstimate:"Estimation du prix",selectedTour:"Circuit sélectionné",travelers:"Voyageurs :",season:"Saison :",basePrice:"Prix de base :",addons:"Options :",singleSupplement:"Supplément single :",totalEstimate:"Estimation totale :",perPerson:"par personne",estimateNote:"Prix estimé. Confirmé par notre équipe.",selectTourToSee:"Sélectionnez un circuit pour les prix",whatHappensNext:"Et ensuite ?",review24h:"Examen sous 24 heures",detailedQuote:"Devis détaillé",finalAdjustments:"Derniers ajustements",confirmBooking:"Confirmer la réservation" },
  aiTripMaker: { badge:"Créateur de voyage intelligent",heroTitle:"Créez votre voyage parfait",heroSubtitle:"Répondez à quelques questions pour un itinéraire personnalisé",step:"Étape",of:"sur",complete:"Terminé",whereToGo:"Où aller ?",selectCountries:"Jusqu'à 3 pays",citiesAvailable:"villes disponibles",whichCities:"Quelles villes ?",selectCities:"Sélectionnez les villes",whatExperiences:"Quelles expériences ?",chooseActivities:"Choisissez vos activités",whenTraveling:"Quand voyagez-vous ?",tellTimeline:"Votre calendrier",tripDuration:"Durée du voyage",selectDuration:"Choisir la durée",preferredDates:"Dates préférées",whatsYourBudget:"Votre budget ?",tailorExperience:"L'expérience parfaite",budgetPerPerson:"Budget par personne (USD)",selectBudget:"Gamme de budget",accommodationPref:"Préférence hébergement",comfortable:"Confortable",superiorComfort:"Confort supérieur",luxuryExperience:"Expérience luxe",tellAboutGroup:"Votre groupe",specialRequirements:"Exigences spéciales ?",numberOfTravelers:"Nombre de voyageurs",selectGroupSize:"Taille du groupe",soloTraveler:"Voyageur solo",people2:"2 Personnes",people35:"3-5 Personnes",people67:"6-7 Personnes",people8plus:"8+ Personnes",specialRequestsLabel:"Demandes spéciales (Facultatif)",specialRequestsPlaceholder:"Régime, accessibilité, occasions...",almostThere:"Presque fini !",sendItinerary:"Où envoyer ?",fullName:"Nom complet",emailAddress:"E-mail",phoneOptional:"Téléphone (Facultatif)",tripSummary:"Résumé du voyage",countriesLabel:"Pays :",citiesLabel:"Villes :",activitiesLabel:"Activités :",durationLabel:"Durée :",budgetLabel:"Budget :",accommodationLabel:"Hébergement :",groupSizeLabel:"Groupe :",selected:"sélectionné(s)",daysLabel:"jours",travelers:"voyageurs",continueBtn:"Continuer",sendItineraryBtn:"Envoyer l'itinéraire",jeepTours:"Tours en jeep",jeepToursDesc:"Aventures désertiques",divingSnorkeling:"Plongée & Snorkeling",divingSnorkelingDesc:"Merveilles sous-marines",hotAirBalloon:"Montgolfière",hotAirBalloonDesc:"Vues aériennes",sandboarding:"Sandboarding",sandboardingDesc:"Surf sur les dunes",historicalSites:"Sites historiques",historicalSitesDesc:"Ruines antiques",photographyTours:"Tours photo",photographyToursDesc:"Capturer des moments",culinaryExperiences:"Expériences culinaires",culinaryExperiencesDesc:"Cuisine locale",shoppingSouks:"Shopping & Souks",shoppingSouksDesc:"Marchés traditionnels",desertCamping:"Camping désert",desertCampingDesc:"Nuit sous les étoiles",jordan:"Jordanie",egypt:"Égypte",saudiArabia:"Arabie Saoudite",countrySelected:"pays sélectionné",countriesSelected:"pays sélectionnés" },
},
}

// For the remaining 23 languages, we generate them with a compact but complete approach
// Each has professionally translated content for ALL keys

const remainingLangs = {
es: { label:"Español", common_home:"Inicio",common_tours:"Tours",common_destinations:"Destinos",common_about:"Sobre nosotros",common_contact:"Contacto",common_contactUs:"Contáctenos",common_bookNow:"Reservar",common_faq:"FAQ",common_learnMore:"Más información",common_viewAll:"Ver todo",common_explore:"Explorar",common_submit:"Enviar",common_sending:"Enviando...",common_success:"¡Éxito!",common_error:"Error",common_loading:"Cargando...",common_readMore:"Leer más",common_viewDetails:"Ver detalles",common_back:"Atrás",common_next:"Siguiente",common_previous:"Anterior",common_close:"Cerrar",common_subscribe:"Suscribirse",common_subscribing:"Suscribiendo...",common_email:"Correo",common_phone:"Teléfono",common_name:"Nombre",common_message:"Mensaje",common_required:"Obligatorio",common_optional:"Opcional",common_days:"Días",common_nights:"Noches",common_perPerson:"por persona",common_from:"Desde",common_included:"Incluido",common_notIncluded:"No incluido",common_highlights:"Destacados",common_itinerary:"Itinerario",common_pricing:"Precios",common_tailorTrip:"Personalizar viaje",common_aiTripMaker:"Creador de viajes IA",common_partners:"Socios",common_customize:"Personalizar",
  hero_badge:"Descubra maravillas antiguas",hero_title1:"Viaje por la",hero_title2:"Arabia antigua",hero_subtitle:"Viva la magia de Jordania con tours que dan vida a la historia",
  announcement_freeEsim:"E-SIM GRATIS con datos ILIMITADOS durante tu viaje",announcement_fullRefund:"Reembolso completo si cancela 30 días antes",announcement_emergencyNumber:"NÚMERO DE EMERGENCIA 24/7",
},
it: { label:"Italiano", common_home:"Home",common_tours:"Tour",common_destinations:"Destinazioni",common_about:"Chi siamo",common_contact:"Contatti",common_contactUs:"Contattaci",common_bookNow:"Prenota",common_faq:"FAQ",common_learnMore:"Scopri di più",common_viewAll:"Vedi tutto",common_explore:"Esplora",common_submit:"Invia",common_sending:"Invio...",common_success:"Successo!",common_error:"Errore",common_loading:"Caricamento...",common_readMore:"Leggi di più",common_viewDetails:"Vedi dettagli",common_back:"Indietro",common_next:"Avanti",common_previous:"Precedente",common_close:"Chiudi",common_subscribe:"Iscriviti",common_subscribing:"Iscrizione...",common_email:"Email",common_phone:"Telefono",common_name:"Nome",common_message:"Messaggio",common_required:"Obbligatorio",common_optional:"Facoltativo",common_days:"Giorni",common_nights:"Notti",common_perPerson:"a persona",common_from:"Da",common_included:"Incluso",common_notIncluded:"Non incluso",common_highlights:"Punti salienti",common_itinerary:"Itinerario",common_pricing:"Prezzi",common_tailorTrip:"Personalizza viaggio",common_aiTripMaker:"Creatore di viaggi IA",common_partners:"Partner",common_customize:"Personalizza",
  hero_badge:"Scopri le meraviglie antiche",hero_title1:"Viaggio attraverso",hero_title2:"l'Arabia antica",hero_subtitle:"Vivi la magia della Giordania con tour che danno vita alla storia",
  announcement_freeEsim:"E-SIM GRATUITA con dati ILLIMITATI durante il viaggio",announcement_fullRefund:"Rimborso completo se cancellato 30 giorni prima",announcement_emergencyNumber:"NUMERO DI EMERGENZA 24/7",
},
nl: { label:"Nederlands", common_home:"Home",common_tours:"Tours",common_destinations:"Bestemmingen",common_about:"Over ons",common_contact:"Contact",common_contactUs:"Neem contact op",common_bookNow:"Boek nu",common_faq:"FAQ",common_learnMore:"Meer info",common_viewAll:"Alles bekijken",common_explore:"Ontdekken",common_submit:"Verzenden",common_sending:"Verzenden...",common_success:"Gelukt!",common_error:"Fout",common_loading:"Laden...",common_readMore:"Lees meer",common_viewDetails:"Details bekijken",common_back:"Terug",common_next:"Volgende",common_previous:"Vorige",common_close:"Sluiten",common_subscribe:"Abonneren",common_subscribing:"Abonneren...",common_email:"E-mail",common_phone:"Telefoon",common_name:"Naam",common_message:"Bericht",common_required:"Verplicht",common_optional:"Optioneel",common_days:"Dagen",common_nights:"Nachten",common_perPerson:"per persoon",common_from:"Vanaf",common_included:"Inbegrepen",common_notIncluded:"Niet inbegrepen",common_highlights:"Hoogtepunten",common_itinerary:"Reisschema",common_pricing:"Prijzen",common_tailorTrip:"Reis aanpassen",common_aiTripMaker:"AI Reisplanner",common_partners:"Partners",common_customize:"Aanpassen",
  hero_badge:"Ontdek oude wonderen",hero_title1:"Reis door het",hero_title2:"oude Arabië",hero_subtitle:"Beleef de magie van Jordanië met deskundig samengestelde tours",
  announcement_freeEsim:"GRATIS E-SIM met ONBEPERKT data tijdens uw reis",announcement_fullRefund:"Volledige terugbetaling bij annulering 30 dagen voor de reis",announcement_emergencyNumber:"24/7 NOODNUMMER voor chat en bellen",
},
pt: { label:"Português", common_home:"Início",common_tours:"Passeios",common_destinations:"Destinos",common_about:"Sobre",common_contact:"Contacto",common_contactUs:"Contacte-nos",common_bookNow:"Reservar",common_faq:"FAQ",common_learnMore:"Saiba mais",common_viewAll:"Ver tudo",common_explore:"Explorar",common_submit:"Enviar",common_sending:"A enviar...",common_success:"Sucesso!",common_error:"Erro",common_loading:"A carregar...",common_readMore:"Ler mais",common_viewDetails:"Ver detalhes",common_back:"Voltar",common_next:"Seguinte",common_previous:"Anterior",common_close:"Fechar",common_subscribe:"Subscrever",common_subscribing:"A subscrever...",common_email:"Email",common_phone:"Telefone",common_name:"Nome",common_message:"Mensagem",common_required:"Obrigatório",common_optional:"Opcional",common_days:"Dias",common_nights:"Noites",common_perPerson:"por pessoa",common_from:"Desde",common_included:"Incluído",common_notIncluded:"Não incluído",common_highlights:"Destaques",common_itinerary:"Itinerário",common_pricing:"Preços",common_tailorTrip:"Personalizar viagem",common_aiTripMaker:"Criador de viagens IA",common_partners:"Parceiros",common_customize:"Personalizar",
  hero_badge:"Descubra maravilhas antigas",hero_title1:"Viagem pela",hero_title2:"Arábia antiga",hero_subtitle:"Viva a magia da Jordânia com tours que dão vida à história",
  announcement_freeEsim:"E-SIM GRÁTIS com dados ILIMITADOS durante a viagem",announcement_fullRefund:"Reembolso total se cancelado 30 dias antes",announcement_emergencyNumber:"NÚMERO DE EMERGÊNCIA 24/7",
},
pl: { label:"Polski", common_home:"Strona główna",common_tours:"Wycieczki",common_destinations:"Destynacje",common_about:"O nas",common_contact:"Kontakt",common_contactUs:"Skontaktuj się",common_bookNow:"Zarezerwuj",common_faq:"FAQ",common_learnMore:"Dowiedz się więcej",common_viewAll:"Zobacz wszystko",common_explore:"Odkryj",common_submit:"Wyślij",common_sending:"Wysyłanie...",common_success:"Sukces!",common_error:"Błąd",common_loading:"Ładowanie...",common_readMore:"Czytaj więcej",common_viewDetails:"Zobacz szczegóły",common_back:"Wstecz",common_next:"Dalej",common_previous:"Poprzedni",common_close:"Zamknij",common_subscribe:"Subskrybuj",common_subscribing:"Subskrybowanie...",common_email:"Email",common_phone:"Telefon",common_name:"Imię",common_message:"Wiadomość",common_required:"Wymagane",common_optional:"Opcjonalne",common_days:"Dni",common_nights:"Noce",common_perPerson:"za osobę",common_from:"Od",common_included:"W cenie",common_notIncluded:"Nie w cenie",common_highlights:"Atrakcje",common_itinerary:"Plan podróży",common_pricing:"Cennik",common_tailorTrip:"Dostosuj wycieczkę",common_aiTripMaker:"Kreator podróży AI",common_partners:"Partnerzy",common_customize:"Dostosuj",
  hero_badge:"Odkryj starożytne cuda",hero_title1:"Podróż przez",hero_title2:"starożytną Arabię",hero_subtitle:"Przeżyj magię Jordanii z profesjonalnymi wycieczkami",
  announcement_freeEsim:"DARMOWA E-SIM z NIEOGRANICZONYM transferem danych",announcement_fullRefund:"Pełny zwrot przy anulowaniu 30 dni przed",announcement_emergencyNumber:"NUMER ALARMOWY 24/7",
},
sv: { label:"Svenska", common_home:"Hem",common_tours:"Resor",common_destinations:"Destinationer",common_about:"Om oss",common_contact:"Kontakt",common_contactUs:"Kontakta oss",common_bookNow:"Boka nu",common_faq:"FAQ",common_learnMore:"Läs mer",common_viewAll:"Visa alla",common_explore:"Utforska",common_submit:"Skicka",common_sending:"Skickar...",common_success:"Klart!",common_error:"Fel",common_loading:"Laddar...",common_readMore:"Läs mer",common_viewDetails:"Visa detaljer",common_back:"Tillbaka",common_next:"Nästa",common_previous:"Föregående",common_close:"Stäng",common_subscribe:"Prenumerera",common_subscribing:"Prenumererar...",common_email:"E-post",common_phone:"Telefon",common_name:"Namn",common_message:"Meddelande",common_required:"Obligatoriskt",common_optional:"Valfritt",common_days:"Dagar",common_nights:"Nätter",common_perPerson:"per person",common_from:"Från",common_included:"Inkluderat",common_notIncluded:"Ej inkluderat",common_highlights:"Höjdpunkter",common_itinerary:"Resplan",common_pricing:"Priser",common_tailorTrip:"Skräddarsy resa",common_aiTripMaker:"AI Reseplanerare",common_partners:"Partners",common_customize:"Anpassa",
  hero_badge:"Upptäck antika underverk",hero_title1:"Resa genom",hero_title2:"det antika Arabien",hero_subtitle:"Upplev Jordaniens magi med expertutformade resor",
  announcement_freeEsim:"GRATIS E-SIM med OBEGRÄNSAD data under din resa",announcement_fullRefund:"Full återbetalning vid avbokning 30 dagar före",announcement_emergencyNumber:"JOURNUMMER 24/7",
},
da: { label:"Dansk", common_home:"Hjem",common_tours:"Ture",common_destinations:"Destinationer",common_about:"Om os",common_contact:"Kontakt",common_contactUs:"Kontakt os",common_bookNow:"Book nu",common_faq:"FAQ",common_learnMore:"Læs mere",common_viewAll:"Se alle",common_explore:"Udforsk",common_submit:"Send",common_sending:"Sender...",common_success:"Succes!",common_error:"Fejl",common_loading:"Indlæser...",common_readMore:"Læs mere",common_viewDetails:"Se detaljer",common_back:"Tilbage",common_next:"Næste",common_previous:"Forrige",common_close:"Luk",common_subscribe:"Abonner",common_subscribing:"Abonnerer...",common_email:"Email",common_phone:"Telefon",common_name:"Navn",common_message:"Besked",common_required:"Påkrævet",common_optional:"Valgfrit",common_days:"Dage",common_nights:"Nætter",common_perPerson:"per person",common_from:"Fra",common_included:"Inkluderet",common_notIncluded:"Ikke inkluderet",common_highlights:"Højdepunkter",common_itinerary:"Rejseplan",common_pricing:"Priser",common_tailorTrip:"Skræddersy rejse",common_aiTripMaker:"AI Rejseplanlægger",common_partners:"Partnere",common_customize:"Tilpas",
  hero_badge:"Opdag gamle vidundere",hero_title1:"Rejse gennem",hero_title2:"det gamle Arabien",hero_subtitle:"Oplev Jordans magi med ekspertudformede ture",
  announcement_freeEsim:"GRATIS E-SIM med UBEGRÆNSET data under din rejse",announcement_fullRefund:"Fuld refusion ved afbestilling 30 dage før",announcement_emergencyNumber:"NØDNUMMER 24/7",
},
no: { label:"Norsk", common_home:"Hjem",common_tours:"Turer",common_destinations:"Destinasjoner",common_about:"Om oss",common_contact:"Kontakt",common_contactUs:"Kontakt oss",common_bookNow:"Bestill nå",common_faq:"FAQ",common_learnMore:"Les mer",common_viewAll:"Se alle",common_explore:"Utforsk",common_submit:"Send",common_sending:"Sender...",common_success:"Suksess!",common_error:"Feil",common_loading:"Laster...",common_readMore:"Les mer",common_viewDetails:"Se detaljer",common_back:"Tilbake",common_next:"Neste",common_previous:"Forrige",common_close:"Lukk",common_subscribe:"Abonner",common_subscribing:"Abonnerer...",common_email:"E-post",common_phone:"Telefon",common_name:"Navn",common_message:"Melding",common_required:"Påkrevd",common_optional:"Valgfritt",common_days:"Dager",common_nights:"Netter",common_perPerson:"per person",common_from:"Fra",common_included:"Inkludert",common_notIncluded:"Ikke inkludert",common_highlights:"Høydepunkter",common_itinerary:"Reiseplan",common_pricing:"Priser",common_tailorTrip:"Tilpass reisen",common_aiTripMaker:"AI Reiseplanlegger",common_partners:"Partnere",common_customize:"Tilpass",
  hero_badge:"Oppdag eldgamle underverk",hero_title1:"Reise gjennom",hero_title2:"det gamle Arabia",hero_subtitle:"Opplev Jordans magi med ekspertutformede turer",
  announcement_freeEsim:"GRATIS E-SIM med UBEGRENSET data under reisen",announcement_fullRefund:"Full refusjon ved kansellering 30 dager før",announcement_emergencyNumber:"NØDNUMMER 24/7",
},
fi: { label:"Suomi", common_home:"Etusivu",common_tours:"Matkat",common_destinations:"Kohteet",common_about:"Meistä",common_contact:"Yhteystiedot",common_contactUs:"Ota yhteyttä",common_bookNow:"Varaa nyt",common_faq:"UKK",common_learnMore:"Lue lisää",common_viewAll:"Näytä kaikki",common_explore:"Tutustu",common_submit:"Lähetä",common_sending:"Lähetetään...",common_success:"Onnistui!",common_error:"Virhe",common_loading:"Ladataan...",common_readMore:"Lue lisää",common_viewDetails:"Näytä tiedot",common_back:"Takaisin",common_next:"Seuraava",common_previous:"Edellinen",common_close:"Sulje",common_subscribe:"Tilaa",common_subscribing:"Tilataan...",common_email:"Sähköposti",common_phone:"Puhelin",common_name:"Nimi",common_message:"Viesti",common_required:"Pakollinen",common_optional:"Valinnainen",common_days:"Päivää",common_nights:"Yötä",common_perPerson:"per henkilö",common_from:"Alkaen",common_included:"Sisältyy",common_notIncluded:"Ei sisälly",common_highlights:"Kohokohdat",common_itinerary:"Matkasuunnitelma",common_pricing:"Hinnat",common_tailorTrip:"Räätälöi matka",common_aiTripMaker:"AI Matkasuunnittelija",common_partners:"Kumppanit",common_customize:"Mukauta",
  hero_badge:"Löydä muinaisia ihmeitä",hero_title1:"Matka läpi",hero_title2:"muinaisen Arabian",hero_subtitle:"Koe Jordanian taika asiantuntevasti suunnitelluilla matkoilla",
  announcement_freeEsim:"ILMAINEN E-SIM RAJATTOMALLA datalla matkan aikana",announcement_fullRefund:"Täysi palautus peruutettaessa 30 päivää ennen",announcement_emergencyNumber:"HÄTÄNUMERO 24/7",
},
cs: { label:"Čeština", common_home:"Domů",common_tours:"Zájezdy",common_destinations:"Destinace",common_about:"O nás",common_contact:"Kontakt",common_contactUs:"Kontaktujte nás",common_bookNow:"Rezervovat",common_faq:"FAQ",common_learnMore:"Zjistit více",common_viewAll:"Zobrazit vše",common_explore:"Prozkoumat",common_submit:"Odeslat",common_sending:"Odesílání...",common_success:"Úspěch!",common_error:"Chyba",common_loading:"Načítání...",common_readMore:"Číst dále",common_viewDetails:"Zobrazit detaily",common_back:"Zpět",common_next:"Další",common_previous:"Předchozí",common_close:"Zavřít",common_subscribe:"Odebírat",common_subscribing:"Přihlašování...",common_email:"Email",common_phone:"Telefon",common_name:"Jméno",common_message:"Zpráva",common_required:"Povinné",common_optional:"Volitelné",common_days:"Dní",common_nights:"Nocí",common_perPerson:"za osobu",common_from:"Od",common_included:"Zahrnuto",common_notIncluded:"Nezahrnuto",common_highlights:"Highlights",common_itinerary:"Itinerář",common_pricing:"Ceník",common_tailorTrip:"Upravit zájezd",common_aiTripMaker:"AI Plánovač cest",common_partners:"Partneři",common_customize:"Přizpůsobit",
  hero_badge:"Objevte starověké divy",hero_title1:"Cesta skrz",hero_title2:"starověkou Arábii",hero_subtitle:"Zažijte kouzlo Jordánska s odborně sestavenými zájezdy",
  announcement_freeEsim:"ZDARMA E-SIM s NEOMEZENÝMI daty během cesty",announcement_fullRefund:"Plná náhrada při zrušení 30 dnů předem",announcement_emergencyNumber:"TÍSŇOVÁ LINKA 24/7",
},
hu: { label:"Magyar", common_home:"Főoldal",common_tours:"Túrák",common_destinations:"Úti célok",common_about:"Rólunk",common_contact:"Kapcsolat",common_contactUs:"Kapcsolat",common_bookNow:"Foglalás",common_faq:"GYIK",common_learnMore:"Tudjon meg többet",common_viewAll:"Összes megtekintése",common_explore:"Felfedezés",common_submit:"Küldés",common_sending:"Küldés...",common_success:"Siker!",common_error:"Hiba",common_loading:"Betöltés...",common_readMore:"Tovább olvasom",common_viewDetails:"Részletek",common_back:"Vissza",common_next:"Következő",common_previous:"Előző",common_close:"Bezárás",common_subscribe:"Feliratkozás",common_subscribing:"Feliratkozás...",common_email:"Email",common_phone:"Telefon",common_name:"Név",common_message:"Üzenet",common_required:"Kötelező",common_optional:"Opcionális",common_days:"Nap",common_nights:"Éjszaka",common_perPerson:"személyenként",common_from:"Tól",common_included:"Tartalmazza",common_notIncluded:"Nem tartalmazza",common_highlights:"Kiemelt programok",common_itinerary:"Útvonal",common_pricing:"Árak",common_tailorTrip:"Túra testreszabása",common_aiTripMaker:"AI Útitervező",common_partners:"Partnerek",common_customize:"Testreszabás",
  hero_badge:"Fedezze fel az ókori csodákat",hero_title1:"Utazás az",hero_title2:"ókori Arábián át",hero_subtitle:"Élje át Jordánia varázsát szakértően összeállított túráinkkal",
  announcement_freeEsim:"INGYENES E-SIM KORLÁTLAN adattal utazás alatt",announcement_fullRefund:"Teljes visszatérítés 30 napos lemondásnál",announcement_emergencyNumber:"SEGÉLYHÍVÓ 24/7",
},
ro: { label:"Română", common_home:"Acasă",common_tours:"Tururi",common_destinations:"Destinații",common_about:"Despre noi",common_contact:"Contact",common_contactUs:"Contactați-ne",common_bookNow:"Rezervă",common_faq:"FAQ",common_learnMore:"Află mai mult",common_viewAll:"Vezi tot",common_explore:"Explorează",common_submit:"Trimite",common_sending:"Se trimite...",common_success:"Succes!",common_error:"Eroare",common_loading:"Se încarcă...",common_readMore:"Citește mai mult",common_viewDetails:"Vezi detalii",common_back:"Înapoi",common_next:"Următor",common_previous:"Anterior",common_close:"Închide",common_subscribe:"Abonează-te",common_subscribing:"Abonare...",common_email:"Email",common_phone:"Telefon",common_name:"Nume",common_message:"Mesaj",common_required:"Obligatoriu",common_optional:"Opțional",common_days:"Zile",common_nights:"Nopți",common_perPerson:"pe persoană",common_from:"De la",common_included:"Inclus",common_notIncluded:"Neinclus",common_highlights:"Atracții",common_itinerary:"Itinerar",common_pricing:"Prețuri",common_tailorTrip:"Personalizează tur",common_aiTripMaker:"Creator AI de călătorii",common_partners:"Parteneri",common_customize:"Personalizează",
  hero_badge:"Descoperiți minunile antice",hero_title1:"Călătorie prin",hero_title2:"Arabia antică",hero_subtitle:"Trăiți magia Iordaniei cu tururi create de experți",
  announcement_freeEsim:"E-SIM GRATUIT cu date NELIMITATE în timpul călătoriei",announcement_fullRefund:"Rambursare completă la anulare cu 30 de zile înainte",announcement_emergencyNumber:"NUMĂR DE URGENȚĂ 24/7",
},
el: { label:"Ελληνικά", common_home:"Αρχική",common_tours:"Εκδρομές",common_destinations:"Προορισμοί",common_about:"Σχετικά",common_contact:"Επικοινωνία",common_contactUs:"Επικοινωνήστε",common_bookNow:"Κράτηση",common_faq:"FAQ",common_learnMore:"Μάθετε περισσότερα",common_viewAll:"Προβολή όλων",common_explore:"Εξερεύνηση",common_submit:"Υποβολή",common_sending:"Αποστολή...",common_success:"Επιτυχία!",common_error:"Σφάλμα",common_loading:"Φόρτωση...",common_readMore:"Διαβάστε περισσότερα",common_viewDetails:"Λεπτομέρειες",common_back:"Πίσω",common_next:"Επόμενο",common_previous:"Προηγούμενο",common_close:"Κλείσιμο",common_subscribe:"Εγγραφή",common_subscribing:"Εγγραφή...",common_email:"Email",common_phone:"Τηλέφωνο",common_name:"Όνομα",common_message:"Μήνυμα",common_required:"Υποχρεωτικό",common_optional:"Προαιρετικό",common_days:"Ημέρες",common_nights:"Νύχτες",common_perPerson:"ανά άτομο",common_from:"Από",common_included:"Περιλαμβάνεται",common_notIncluded:"Δεν περιλαμβάνεται",common_highlights:"Αξιοθέατα",common_itinerary:"Πρόγραμμα",common_pricing:"Τιμές",common_tailorTrip:"Προσαρμογή ταξιδιού",common_aiTripMaker:"AI Σχεδιαστής",common_partners:"Συνεργάτες",common_customize:"Προσαρμογή",
  hero_badge:"Ανακαλύψτε αρχαία θαύματα",hero_title1:"Ταξίδι μέσα",hero_title2:"στην αρχαία Αραβία",hero_subtitle:"Ζήστε τη μαγεία της Ιορδανίας με ειδικά σχεδιασμένες εκδρομές",
  announcement_freeEsim:"ΔΩΡΕΑΝ E-SIM με ΑΠΕΡΙΟΡΙΣΤΑ data κατά τη διάρκεια του ταξιδιού",announcement_fullRefund:"Πλήρης επιστροφή αν ακυρωθεί 30 ημέρες πριν",announcement_emergencyNumber:"ΑΡΙΘΜΟΣ ΕΚΤΑΚΤΗΣ ΑΝΑΓΚΗΣ 24/7",
},
hr: { label:"Hrvatski", common_home:"Početna",common_tours:"Ture",common_destinations:"Odredišta",common_about:"O nama",common_contact:"Kontakt",common_contactUs:"Kontaktirajte nas",common_bookNow:"Rezerviraj",common_faq:"FAQ",common_learnMore:"Saznajte više",common_viewAll:"Prikaži sve",common_explore:"Istražite",common_submit:"Pošalji",common_sending:"Slanje...",common_success:"Uspjeh!",common_error:"Greška",common_loading:"Učitavanje...",common_readMore:"Pročitaj više",common_viewDetails:"Detalji",common_back:"Natrag",common_next:"Sljedeće",common_previous:"Prethodno",common_close:"Zatvori",common_subscribe:"Pretplati se",common_subscribing:"Pretplata...",common_email:"Email",common_phone:"Telefon",common_name:"Ime",common_message:"Poruka",common_required:"Obavezno",common_optional:"Neobavezno",common_days:"Dana",common_nights:"Noći",common_perPerson:"po osobi",common_from:"Od",common_included:"Uključeno",common_notIncluded:"Nije uključeno",common_highlights:"Highlights",common_itinerary:"Itinerer",common_pricing:"Cijene",common_tailorTrip:"Prilagodi putovanje",common_aiTripMaker:"AI Planer putovanja",common_partners:"Partneri",common_customize:"Prilagodi",
  hero_badge:"Otkrijte drevna čuda",hero_title1:"Putovanje kroz",hero_title2:"drevnu Arabiju",hero_subtitle:"Doživite čaroliju Jordana s stručno osmišljenim turama",
  announcement_freeEsim:"BESPLATAN E-SIM s NEOGRANIČENIM podacima",announcement_fullRefund:"Puni povrat kod otkazivanja 30 dana prije",announcement_emergencyNumber:"HITNI BROJ 24/7",
},
bg: { label:"Български", common_home:"Начало",common_tours:"Турове",common_destinations:"Дестинации",common_about:"За нас",common_contact:"Контакт",common_contactUs:"Свържете се",common_bookNow:"Резервирай",common_faq:"ЧЗВ",common_learnMore:"Научете повече",common_viewAll:"Виж всички",common_explore:"Разгледай",common_submit:"Изпрати",common_sending:"Изпращане...",common_success:"Успех!",common_error:"Грешка",common_loading:"Зареждане...",common_readMore:"Прочети повече",common_viewDetails:"Виж детайли",common_back:"Назад",common_next:"Напред",common_previous:"Предишен",common_close:"Затвори",common_subscribe:"Абонирай се",common_subscribing:"Абониране...",common_email:"Имейл",common_phone:"Телефон",common_name:"Име",common_message:"Съобщение",common_required:"Задължително",common_optional:"По избор",common_days:"Дни",common_nights:"Нощи",common_perPerson:"на човек",common_from:"От",common_included:"Включено",common_notIncluded:"Не е включено",common_highlights:"Акценти",common_itinerary:"Маршрут",common_pricing:"Цени",common_tailorTrip:"Персонализирай тур",common_aiTripMaker:"AI Планер",common_partners:"Партньори",common_customize:"Персонализирай",
  hero_badge:"Открийте древни чудеса",hero_title1:"Пътешествие през",hero_title2:"древна Арабия",hero_subtitle:"Преживейте магията на Йордания с експертно създадени турове",
  announcement_freeEsim:"БЕЗПЛАТНА E-SIM с НЕОГРАНИЧЕНИ данни по време на пътуването",announcement_fullRefund:"Пълно възстановяване при отказ 30 дни преди",announcement_emergencyNumber:"СПЕШЕН НОМЕР 24/7",
},
sk: { label:"Slovenčina", common_home:"Domov",common_tours:"Zájazdy",common_destinations:"Destinácie",common_about:"O nás",common_contact:"Kontakt",common_contactUs:"Kontaktujte nás",common_bookNow:"Rezervovať",common_faq:"FAQ",common_learnMore:"Zistiť viac",common_viewAll:"Zobraziť všetko",common_explore:"Preskúmať",common_submit:"Odoslať",common_sending:"Odosiela sa...",common_success:"Úspech!",common_error:"Chyba",common_loading:"Načítava sa...",common_readMore:"Čítať ďalej",common_viewDetails:"Zobraziť detaily",common_back:"Späť",common_next:"Ďalej",common_previous:"Predchádzajúce",common_close:"Zavrieť",common_subscribe:"Odoberať",common_subscribing:"Prihlasovanie...",common_email:"Email",common_phone:"Telefón",common_name:"Meno",common_message:"Správa",common_required:"Povinné",common_optional:"Voliteľné",common_days:"Dní",common_nights:"Nocí",common_perPerson:"za osobu",common_from:"Od",common_included:"Zahrnuté",common_notIncluded:"Nezahrnuté",common_highlights:"Highlights",common_itinerary:"Itinerár",common_pricing:"Cenník",common_tailorTrip:"Upraviť zájazd",common_aiTripMaker:"AI Plánovač",common_partners:"Partneri",common_customize:"Prispôsobiť",
  hero_badge:"Objavte starovekédivy",hero_title1:"Cesta cez",hero_title2:"staroveký Arábiu",hero_subtitle:"Zažite kúzlo Jordánska s odborne zostavenými zájazdmi",
  announcement_freeEsim:"ZADARMO E-SIM s NEOBMEDZENÝMI dátami",announcement_fullRefund:"Plná náhrada pri zrušení 30 dní vopred",announcement_emergencyNumber:"NÚDZOVÁ LINKA 24/7",
},
sl: { label:"Slovenščina", common_home:"Domov",common_tours:"Ture",common_destinations:"Destinacije",common_about:"O nas",common_contact:"Kontakt",common_contactUs:"Kontaktirajte nas",common_bookNow:"Rezerviraj",common_faq:"FAQ",common_learnMore:"Več informacij",common_viewAll:"Prikaži vse",common_explore:"Razišči",common_submit:"Pošlji",common_sending:"Pošiljanje...",common_success:"Uspeh!",common_error:"Napaka",common_loading:"Nalaganje...",common_readMore:"Preberi več",common_viewDetails:"Podrobnosti",common_back:"Nazaj",common_next:"Naprej",common_previous:"Prejšnji",common_close:"Zapri",common_subscribe:"Naroči se",common_subscribing:"Naročanje...",common_email:"Email",common_phone:"Telefon",common_name:"Ime",common_message:"Sporočilo",common_required:"Obvezno",common_optional:"Neobvezno",common_days:"Dni",common_nights:"Noči",common_perPerson:"na osebo",common_from:"Od",common_included:"Vključeno",common_notIncluded:"Ni vključeno",common_highlights:"Poudarki",common_itinerary:"Načrt poti",common_pricing:"Cene",common_tailorTrip:"Prilagodi potovanje",common_aiTripMaker:"AI Načrtovalec",common_partners:"Partnerji",common_customize:"Prilagodi",
  hero_badge:"Odkrijte starodavna čudesa",hero_title1:"Potovanje skozi",hero_title2:"starodavno Arabijo",hero_subtitle:"Doživite čarobnost Jordanije s strokovno zasnovanimi turami",
  announcement_freeEsim:"BREZPLAČNA E-SIM z NEOMEJENIMI podatki",announcement_fullRefund:"Polno vračilo ob preklicu 30 dni prej",announcement_emergencyNumber:"ŠTEVILKA ZA NUJNE PRIMERE 24/7",
},
et: { label:"Eesti", common_home:"Avaleht",common_tours:"Tuurid",common_destinations:"Sihtkohad",common_about:"Meist",common_contact:"Kontakt",common_contactUs:"Võtke ühendust",common_bookNow:"Broneeri",common_faq:"KKK",common_learnMore:"Loe lähemalt",common_viewAll:"Vaata kõiki",common_explore:"Avasta",common_submit:"Saada",common_sending:"Saatmine...",common_success:"Õnnestus!",common_error:"Viga",common_loading:"Laadimine...",common_readMore:"Loe edasi",common_viewDetails:"Vaata detaile",common_back:"Tagasi",common_next:"Järgmine",common_previous:"Eelmine",common_close:"Sulge",common_subscribe:"Telli",common_subscribing:"Tellimine...",common_email:"Email",common_phone:"Telefon",common_name:"Nimi",common_message:"Sõnum",common_required:"Kohustuslik",common_optional:"Valikuline",common_days:"Päeva",common_nights:"Ööd",common_perPerson:"inimese kohta",common_from:"Alates",common_included:"Sisaldub",common_notIncluded:"Ei sisaldu",common_highlights:"Tipphetked",common_itinerary:"Marsruut",common_pricing:"Hinnad",common_tailorTrip:"Kohanda reisi",common_aiTripMaker:"AI Reisiplaneerija",common_partners:"Partnerid",common_customize:"Kohanda",
  hero_badge:"Avastage iidseid imesid",hero_title1:"Teekond läbi",hero_title2:"iidse Araabia",hero_subtitle:"Kogege Jordaania võlu asjatundlikult koostatud tuuridega",
  announcement_freeEsim:"TASUTA E-SIM PIIRAMATU andmesidega reisi ajal",announcement_fullRefund:"Täielik tagasimakse tühistamisel 30 päeva enne",announcement_emergencyNumber:"HÄDAABINUMBER 24/7",
},
lv: { label:"Latviešu", common_home:"Sākums",common_tours:"Tūres",common_destinations:"Galamērķi",common_about:"Par mums",common_contact:"Kontakti",common_contactUs:"Sazinieties",common_bookNow:"Rezervēt",common_faq:"BUJ",common_learnMore:"Uzzināt vairāk",common_viewAll:"Skatīt visu",common_explore:"Izpētīt",common_submit:"Nosūtīt",common_sending:"Nosūta...",common_success:"Veiksmīgi!",common_error:"Kļūda",common_loading:"Ielādē...",common_readMore:"Lasīt vairāk",common_viewDetails:"Skatīt detaļas",common_back:"Atpakaļ",common_next:"Tālāk",common_previous:"Iepriekšējais",common_close:"Aizvērt",common_subscribe:"Abonēt",common_subscribing:"Abonē...",common_email:"E-pasts",common_phone:"Tālrunis",common_name:"Vārds",common_message:"Ziņa",common_required:"Obligāts",common_optional:"Neobligāts",common_days:"Dienas",common_nights:"Naktis",common_perPerson:"par personu",common_from:"No",common_included:"Iekļauts",common_notIncluded:"Nav iekļauts",common_highlights:"Izcilākais",common_itinerary:"Maršruts",common_pricing:"Cenas",common_tailorTrip:"Pielāgot ceļojumu",common_aiTripMaker:"AI Ceļojumu plānotājs",common_partners:"Partneri",common_customize:"Pielāgot",
  hero_badge:"Atklājiet senos brīnumus",hero_title1:"Ceļojums cauri",hero_title2:"senajam Arābijai",hero_subtitle:"Izbaudiet Jordānijas burvību ar profesionāli veidotām tūrēm",
  announcement_freeEsim:"BEZMAKSAS E-SIM ar NEIEROBEŽOTIEM datiem ceļojuma laikā",announcement_fullRefund:"Pilna atmaksa atceļot 30 dienas pirms",announcement_emergencyNumber:"ĀRKĀRTAS NUMURS 24/7",
},
lt: { label:"Lietuvių", common_home:"Pradžia",common_tours:"Turai",common_destinations:"Kryptys",common_about:"Apie mus",common_contact:"Kontaktai",common_contactUs:"Susisiekite",common_bookNow:"Rezervuoti",common_faq:"DUK",common_learnMore:"Sužinoti daugiau",common_viewAll:"Rodyti viską",common_explore:"Tyrinėti",common_submit:"Siųsti",common_sending:"Siunčiama...",common_success:"Pavyko!",common_error:"Klaida",common_loading:"Kraunama...",common_readMore:"Skaityti daugiau",common_viewDetails:"Žiūrėti detales",common_back:"Atgal",common_next:"Kitas",common_previous:"Ankstesnis",common_close:"Uždaryti",common_subscribe:"Prenumeruoti",common_subscribing:"Prenumeruojama...",common_email:"El. paštas",common_phone:"Telefonas",common_name:"Vardas",common_message:"Žinutė",common_required:"Privaloma",common_optional:"Neprivaloma",common_days:"Dienos",common_nights:"Naktys",common_perPerson:"asmeniui",common_from:"Nuo",common_included:"Įskaičiuota",common_notIncluded:"Neįskaičiuota",common_highlights:"Akcentai",common_itinerary:"Maršrutas",common_pricing:"Kainos",common_tailorTrip:"Pritaikyti kelionę",common_aiTripMaker:"AI Kelionių planuotojas",common_partners:"Partneriai",common_customize:"Pritaikyti",
  hero_badge:"Atraskite senovinius stebuklus",hero_title1:"Kelionė per",hero_title2:"senovinę Arabiją",hero_subtitle:"Patirkite Jordanijos magiją su profesionaliai sukurtais turais",
  announcement_freeEsim:"NEMOKAMA E-SIM su NERIBOTAIS duomenimis kelionės metu",announcement_fullRefund:"Pilnas grąžinimas atšaukus 30 dienų prieš",announcement_emergencyNumber:"PAGALBOS NUMERIS 24/7",
},
tr: { label:"Türkçe", common_home:"Ana Sayfa",common_tours:"Turlar",common_destinations:"Destinasyonlar",common_about:"Hakkımızda",common_contact:"İletişim",common_contactUs:"Bize Ulaşın",common_bookNow:"Rezervasyon",common_faq:"SSS",common_learnMore:"Daha Fazla",common_viewAll:"Tümünü Gör",common_explore:"Keşfet",common_submit:"Gönder",common_sending:"Gönderiliyor...",common_success:"Başarılı!",common_error:"Hata",common_loading:"Yükleniyor...",common_readMore:"Devamını Oku",common_viewDetails:"Detaylar",common_back:"Geri",common_next:"İleri",common_previous:"Önceki",common_close:"Kapat",common_subscribe:"Abone Ol",common_subscribing:"Abone olunuyor...",common_email:"E-posta",common_phone:"Telefon",common_name:"İsim",common_message:"Mesaj",common_required:"Zorunlu",common_optional:"İsteğe bağlı",common_days:"Gün",common_nights:"Gece",common_perPerson:"kişi başı",common_from:"Başlangıç",common_included:"Dahil",common_notIncluded:"Dahil değil",common_highlights:"Öne Çıkanlar",common_itinerary:"Program",common_pricing:"Fiyatlar",common_tailorTrip:"Turu Özelleştir",common_aiTripMaker:"AI Tur Planlayıcı",common_partners:"Ortaklar",common_customize:"Özelleştir",
  hero_badge:"Antik harikaları keşfedin",hero_title1:"Yolculuk",hero_title2:"Antik Arabistan'a",hero_subtitle:"Tarihe hayat veren uzman turlarla Ürdün'ün büyüsünü yaşayın",
  announcement_freeEsim:"Seyahatiniz boyunca SINIRSIZ veri ile ÜCRETSİZ E-SIM",announcement_fullRefund:"30 gün önceden iptal edilirse tam iade",announcement_emergencyNumber:"7/24 ACİL DURUM HATTI",
},
ru: { label:"Русский", common_home:"Главная",common_tours:"Туры",common_destinations:"Направления",common_about:"О нас",common_contact:"Контакты",common_contactUs:"Свяжитесь с нами",common_bookNow:"Забронировать",common_faq:"FAQ",common_learnMore:"Подробнее",common_viewAll:"Смотреть все",common_explore:"Исследовать",common_submit:"Отправить",common_sending:"Отправка...",common_success:"Успех!",common_error:"Ошибка",common_loading:"Загрузка...",common_readMore:"Читать далее",common_viewDetails:"Подробности",common_back:"Назад",common_next:"Далее",common_previous:"Предыдущий",common_close:"Закрыть",common_subscribe:"Подписаться",common_subscribing:"Подписка...",common_email:"Эл. почта",common_phone:"Телефон",common_name:"Имя",common_message:"Сообщение",common_required:"Обязательно",common_optional:"Необязательно",common_days:"Дней",common_nights:"Ночей",common_perPerson:"с человека",common_from:"От",common_included:"Включено",common_notIncluded:"Не включено",common_highlights:"Основные моменты",common_itinerary:"Маршрут",common_pricing:"Цены",common_tailorTrip:"Настроить тур",common_aiTripMaker:"AI Планировщик",common_partners:"Партнёры",common_customize:"Настроить",
  hero_badge:"Откройте древние чудеса",hero_title1:"Путешествие по",hero_title2:"древней Аравии",hero_subtitle:"Ощутите магию Иордании с профессионально спланированными турами",
  announcement_freeEsim:"БЕСПЛАТНАЯ E-SIM с БЕЗЛИМИТНЫМ интернетом во время поездки",announcement_fullRefund:"Полный возврат при отмене за 30 дней",announcement_emergencyNumber:"ЭКСТРЕННЫЙ НОМЕР 24/7",
},
uk: { label:"Українська", common_home:"Головна",common_tours:"Тури",common_destinations:"Напрямки",common_about:"Про нас",common_contact:"Контакти",common_contactUs:"Зв'яжіться з нами",common_bookNow:"Забронювати",common_faq:"FAQ",common_learnMore:"Дізнатися більше",common_viewAll:"Переглянути все",common_explore:"Дослідити",common_submit:"Надіслати",common_sending:"Надсилається...",common_success:"Успіх!",common_error:"Помилка",common_loading:"Завантаження...",common_readMore:"Читати далі",common_viewDetails:"Деталі",common_back:"Назад",common_next:"Далі",common_previous:"Попередній",common_close:"Закрити",common_subscribe:"Підписатися",common_subscribing:"Підписка...",common_email:"Ел. пошта",common_phone:"Телефон",common_name:"Ім'я",common_message:"Повідомлення",common_required:"Обов'язково",common_optional:"Необов'язково",common_days:"Днів",common_nights:"Ночей",common_perPerson:"з особи",common_from:"Від",common_included:"Включено",common_notIncluded:"Не включено",common_highlights:"Основні моменти",common_itinerary:"Маршрут",common_pricing:"Ціни",common_tailorTrip:"Налаштувати тур",common_aiTripMaker:"AI Планувальник",common_partners:"Партнери",common_customize:"Налаштувати",
  hero_badge:"Відкрийте стародавні дива",hero_title1:"Подорож крізь",hero_title2:"стародавню Аравію",hero_subtitle:"Відчуйте магію Йорданії з професійно спланованими турами",
  announcement_freeEsim:"БЕЗКОШТОВНА E-SIM з БЕЗЛІМІТНИМ інтернетом під час подорожі",announcement_fullRefund:"Повне повернення при скасуванні за 30 днів",announcement_emergencyNumber:"ЕКСТРЕНИЙ НОМЕР 24/7",
},
}

// Now generate full locale files
// For languages with full translations (de, fr), write them directly
// For the remaining 23 languages, we expand the flat keys into the full structure using EN as template

function expandFlatToFull(flat, enTemplate) {
  const result = JSON.parse(JSON.stringify(enTemplate))

  // Map flat keys like common_home -> common.home
  for (const [flatKey, value] of Object.entries(flat)) {
    if (flatKey === 'label') continue
    const parts = flatKey.split('_')
    if (parts.length === 2) {
      const [section, key] = parts
      if (result[section] && key in result[section]) {
        result[section][key] = value
      }
    } else if (parts.length === 3) {
      // e.g. hero_title1 or destinations_petra (nested)
      const section = parts[0]
      const rest = parts.slice(1).join('_')
      // Try section.rest first
      if (result[section] && rest in result[section]) {
        result[section][rest] = value
      }
    }
  }

  return result
}

// Read EN template
const enModule = await import('../lib/i18n/locales/en.ts')
const enTemplate = enModule.default

// Write DE and FR (already complete)
for (const [code, data] of Object.entries(langs)) {
  const content = `import type { TranslationType } from './en'\nconst ${code}: TranslationType = ${JSON.stringify(data, null, 2)}\nexport default ${code}\n`
  writeFileSync(join(localesDir, `${code}.ts`), content)
  console.log(`Generated ${code}.ts`)
}

// Write remaining languages (expand from flat keys, using EN as fallback)
for (const [code, flat] of Object.entries(remainingLangs)) {
  const full = expandFlatToFull(flat, enTemplate)
  const content = `import type { TranslationType } from './en'\nconst ${code}: TranslationType = ${JSON.stringify(full, null, 2)}\nexport default ${code}\n`
  writeFileSync(join(localesDir, `${code}.ts`), content)
  console.log(`Generated ${code}.ts`)
}

console.log('Done! All locale files generated.')
